server:
  port: 8090
spring:
  application:
    name : gateway-service
zuul:
  ribbon:
  ribbon-isolation-strategy: thread
  ignored-services: '*'
  sensitive-headers: Cookie, Set-Cookie
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  routes:
    farmacy-microservice :
      path : /api/farmacy/**
      serviceId : farmacy-microservice
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka